---
title: "My Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```


Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
  count (aisle) %>% 
  filter ( n > 10000) %>% 
  plot_ly(x = ~aisle, y= ~n, color = ~aisle, type = "scatter")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter (aisle == c("fresh fruits", "fresh vegetables", "packaged vegetables fruits")) %>%
  group_by (aisle, product_name) %>% 
  summarize(n = n()) %>% 
  filter (min_rank(desc(n)) < 4) %>% 
  plot_ly(x = ~aisle, y = ~n, type = "bar")
```

### Chart C

```{r}
instacart %>% 
  sample_n(10) %>%
  group_by(product_name, order_dow) %>% 
  summarize (mean=mean(order_hour_of_day)) %>% 
  plot_ly(x = ~mean, y = ~product_name, type= "scatter", mode = "line")
```



