---
title: "Experience"
output: 
  html_document:
    toc: true
    toc_float: true
---
<h1>Arielle T. Coq, MPH</h1> 
<h2>New york, NY</h2> 
<h3>Tel: 845-264-2353</h3> 
<h4>Email Primary: arielle.coq@gmail.com </h4> 
<h5>Email Secondary: ac4140@cumc.columbia.edu</h5> 

<div class="fluid-row" id="header"

</div>
<div id="Profile" class="section level1">
<h1>Profile</h1>

I am a professional Epidemiologist with a Master of Public Health from the Mailman School of Public Health at Columbia University. During my time at Mailman, I conducted extensive research on breast cancer, which was also the focus of my thesis. I also have international research experience spanning from my internship in France where I spent a summer studying the assessment of the contraction of Hepatitis C among people who inject drugs in various European countries. These substantive experiences have provided me with a wealth of opportunities to analyze quantitative and qualitative data together as I have been able to utilize statistical platforms such as RStudio, GIS and Dedoose to preform exploratory analyses and predictive modeling. I am striving to collaborate and grow in an innovative and dynamic environment and I believe the skills I have acquired through my various classes and experiences will make me a tremendous asset to your organization. 

</center> 

<h1>Education</h1>
#### Columbia University, Mailman School of Public Health                - May 2020
 * Master of Public Health
    - Department – Epidemiology 
    - Certificate – Epidemiology of Chronic Disease 
        
#### State University of New York at Albany                              - May 2018
 * Bachelor of Scinece
    - Major – Public Health     
    - Minor - Biology   
    - Minor- Emergency Preparedness, Homeland Security and Cyber security	
        
#### Our Lady of Lourdes High School                                    - June 2014
  * Regents Diploma
    - Honors	                            
    
</center> 

<h1>Employment and Internships</h1>    

#### Columbia University, Mailman School of Public Health  
 * Location - Washington Heights, NY
 * Time - Summer 2018 - October 2020
 * Title -Graduate Research Assistant 
      -	Collected and analyzed data for breast cancer research in Hispanic population.
      -	Conduct qualitative analysis using Dedoose for assessing main themes for 25 phone interviews. 
      -	Review and audit transcripts to ensure they are consistent with current research projects.
      -	Facilitated quantitative analysis using SAS and RStudio on preliminary findings on Sister Study Project and HINTS Manuscript. 
      -	Utilize Microsoft Access to conduct data analysis & cleaning of women’s mammogram and BIRAD reports 
      -	Effectively communicate with a multi disciplinary team of health care facilities to obtain external data from health care facilities on participants.
      -	Train new employees on various platforms and conducting data analysis and data cleaning measures. 
      
#### Aix- Marseille Université - Sciences Economiques et Sociales de la Santé and Traitment de I’Information  Médical	- Marseille, France	 - Summer  2019
* Research Intern
    -	Analyzed and compiled preliminary data using SAS in a study on drug-users in four European countries. 
    -	Drafted the abstract for the study to be published. 
    -	Developed presentations of findings to be reviewed weekly by the principal investigator and other team members. 
    -	Created and presented research poster of preliminary findings.

#### Columbia University - Mailman School of Public Health - Herbert Irving Comprehensive Cancer Center (HICCC) Cure Program  - Fall 2015- 2018  
* Research Intern
    – Utilized SAS and Dedoose software; collected, analyzed and compiled data for breast cancer research in Hispanic women population of Washington Heights, NY. 
    -	Completed formal presentations and provided weekly status updates of data collected. Used information obtained to draft abstract for the research.

#### The CAS Store    							                       -Fall 2015- 2018  
* Clerk 
    -	Assisted students and faculty in obtaining laboratory supplies from the College of Arts & Science (CAS) Store. 
    -	Conducted inventory of the store products.
    -	Provided customer service to professors and students.
    -	Used Access database to manage store orders and packages.
    -	Trained new employees on store procedures and etiquette.
    
#### Department of Health: Bureau of Communicable Disease Control         - Fall 2017
* Student Intern 
    - Interviewed patients that had acquired recent food-borne illnesses. 
    -	Compiled and cleaned the data for review. 
    -	Followed up on individuals with possible exposure to identify risk of infection.

#### Franklin County Family Health Center 				                    - Summer 2015
* Medical Assistant 
    - Assisted all clinicians with patient care 

</center> 

<h1>Publications</h1> 

Pacsi‐Sepulveda, A. L., Shelton, R. C., Rodriguez, C. B., Coq, A. T., & Tehranifar, P. (2019). “You probably can’t feel as safe as normal women”: Hispanic women’s reactions to breast density notification. Cancer, 125(12), 2049–2056. doi: 10.1002/cncr.32002


</center> 

<h1>Other Relevant Information</h1>

<details>
<summary> Proficient in the following Skills</summary>
<li>SAS</li>
<li>R Studio</li>
<li>GIS</li>
<li>Dedoose</li>
<li>Microsoft Office</li></li>
<ul>Word</li></ul></ul>
<ul>PowerPoint</li></ul></ul>
<ul>Excel</li></ul>
<ul>Access</li></ul>
<ul>Outlook</li></ul>
</details>

<details>
<summary>Relative Coursework</summary>
<li>Columbia CORE</li>
<li>SAS Course</li></ul>
<li>Epidemiology II & III</li></ul>
<li>Epidemiology in Chronic Disease</li></ul>
<li>Machine Learning in Epidemiology</li></ul>
<li>Data Science</li></ul>
<li>GIS</li></ul>
<li>Biology I & II</li></ul>
<li>Introduction to Public Policy</li></ul>
<li>Chemistry I & II</li></ul>
</details>

<details>
<summary>Certificates</summary>
<li>CITI- TC0087 “Human Subject Protection Training”</li>
<li>HIPPA- TC0019: “Health Insurance Portability Accountability Act Research Training Course”</li>
</details>

<details>
<summary>Membership</summary>
<li>Vice President of Columbia Women Leaders</li>
<li>Member of the National Society of Leadership and Success</li>
</details>

</center> 

<h1>Other websites</h1> 

https://mm5351.github.io/foodjusticenyc.github.io/

The website below was done for a class assignment. My group members and I were curious of food insecurities in the five boroughs of New York. We assessed the rates of food insecurity in each borough and did some explaratory analysis on the data that we found. We also created a page that would provide resources to indviduals with healthy food choices for each borough. 

