---
title: "Plot_ly"
output: 
  html_document:
    toc: true
    toc_float: true
---

### Examples

These examples as well as the dashboard in the next tab are done using the plotly library in R studio. A dataset called instacart was used to produce the following graphs below as well as the ones produced in the dashboard. 

```{r}
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
```

Scatter Graph
```{r}
instacart %>% 
  count (aisle) %>% 
  filter ( n > 10000) %>% 
  plot_ly(x = ~aisle, y= ~n, color = ~aisle, type = "scatter")
```

Bar Graph 
```{r}
instacart %>% 
  filter (aisle == c("fresh fruits", "fresh vegetables", "packaged vegetables fruits")) %>%
  group_by (aisle, product_name) %>% 
  summarize(n = n()) %>% 
  filter (min_rank(desc(n)) < 4) %>% 
  plot_ly(x = ~aisle, y = ~n, type = "bar")
```

Line Graph
```{r}
instacart %>% 
  sample_n(10) %>%
  group_by(product_name, order_dow) %>% 
  summarize (mean=mean(order_hour_of_day)) %>% 
  plot_ly(x = ~mean, y = ~product_name, type= "scatter", mode = "line")
```


